// Code generated by Fern. DO NOT EDIT.

package client

import (
	contacts "github.com/informlyco/informly-go/contacts"
	core "github.com/informlyco/informly-go/core"
	internal "github.com/informlyco/informly-go/internal"
	option "github.com/informlyco/informly-go/option"
	segments "github.com/informlyco/informly-go/segments"
)

type Client struct {
	Contacts *contacts.Client
	Segments *segments.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Contacts: contacts.NewClient(options),
		Segments: segments.NewClient(options),
		options:  options,
		baseURL:  options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
