// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/informlyco/informly-go/internal"
	big "math/big"
	time "time"
)

var (
	createContactFieldEmail     = big.NewInt(1 << 0)
	createContactFieldPhone     = big.NewInt(1 << 1)
	createContactFieldFirstname = big.NewInt(1 << 2)
	createContactFieldLastname  = big.NewInt(1 << 3)
	createContactFieldJobtitle  = big.NewInt(1 << 4)
	createContactFieldCompany   = big.NewInt(1 << 5)
)

type CreateContact struct {
	Email     *string `json:"email,omitempty" url:"-"`
	Phone     *string `json:"phone,omitempty" url:"-"`
	Firstname *string `json:"firstname,omitempty" url:"-"`
	Lastname  *string `json:"lastname,omitempty" url:"-"`
	Jobtitle  *string `json:"jobtitle,omitempty" url:"-"`
	Company   *string `json:"company,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateContact) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateContact) SetEmail(email *string) {
	c.Email = email
	c.require(createContactFieldEmail)
}

// SetPhone sets the Phone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateContact) SetPhone(phone *string) {
	c.Phone = phone
	c.require(createContactFieldPhone)
}

// SetFirstname sets the Firstname field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateContact) SetFirstname(firstname *string) {
	c.Firstname = firstname
	c.require(createContactFieldFirstname)
}

// SetLastname sets the Lastname field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateContact) SetLastname(lastname *string) {
	c.Lastname = lastname
	c.require(createContactFieldLastname)
}

// SetJobtitle sets the Jobtitle field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateContact) SetJobtitle(jobtitle *string) {
	c.Jobtitle = jobtitle
	c.require(createContactFieldJobtitle)
}

// SetCompany sets the Company field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateContact) SetCompany(company *string) {
	c.Company = company
	c.require(createContactFieldCompany)
}

func (c *CreateContact) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateContact
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateContact(body)
	return nil
}

func (c *CreateContact) MarshalJSON() ([]byte, error) {
	type embed CreateContact
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getContactRequestFieldID = big.NewInt(1 << 0)
)

type GetContactRequest struct {
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetContactRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetContactRequest) SetID(id string) {
	g.ID = id
	g.require(getContactRequestFieldID)
}

var (
	listContactsRequestFieldPage     = big.NewInt(1 << 0)
	listContactsRequestFieldPageSize = big.NewInt(1 << 1)
)

type ListContactsRequest struct {
	Page     *int `json:"-" url:"page,omitempty"`
	PageSize *int `json:"-" url:"pageSize,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListContactsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListContactsRequest) SetPage(page *int) {
	l.Page = page
	l.require(listContactsRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListContactsRequest) SetPageSize(pageSize *int) {
	l.PageSize = pageSize
	l.require(listContactsRequestFieldPageSize)
}

var (
	contactFieldID             = big.NewInt(1 << 0)
	contactFieldEmail          = big.NewInt(1 << 1)
	contactFieldPhone          = big.NewInt(1 << 2)
	contactFieldContact        = big.NewInt(1 << 3)
	contactFieldOrganizationID = big.NewInt(1 << 4)
	contactFieldCreatedAt      = big.NewInt(1 << 5)
	contactFieldUpdatedAt      = big.NewInt(1 << 6)
)

type Contact struct {
	ID             string          `json:"id" url:"id"`
	Email          *string         `json:"email,omitempty" url:"email,omitempty"`
	Phone          *string         `json:"phone,omitempty" url:"phone,omitempty"`
	Contact        *ContactContact `json:"contact" url:"contact"`
	OrganizationID string          `json:"organizationId" url:"organizationId"`
	CreatedAt      time.Time       `json:"createdAt" url:"createdAt"`
	UpdatedAt      time.Time       `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *Contact) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *Contact) GetEmail() *string {
	if c == nil {
		return nil
	}
	return c.Email
}

func (c *Contact) GetPhone() *string {
	if c == nil {
		return nil
	}
	return c.Phone
}

func (c *Contact) GetContact() *ContactContact {
	if c == nil {
		return nil
	}
	return c.Contact
}

func (c *Contact) GetOrganizationID() string {
	if c == nil {
		return ""
	}
	return c.OrganizationID
}

func (c *Contact) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *Contact) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}

func (c *Contact) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *Contact) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Contact) SetID(id string) {
	c.ID = id
	c.require(contactFieldID)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Contact) SetEmail(email *string) {
	c.Email = email
	c.require(contactFieldEmail)
}

// SetPhone sets the Phone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Contact) SetPhone(phone *string) {
	c.Phone = phone
	c.require(contactFieldPhone)
}

// SetContact sets the Contact field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Contact) SetContact(contact *ContactContact) {
	c.Contact = contact
	c.require(contactFieldContact)
}

// SetOrganizationID sets the OrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Contact) SetOrganizationID(organizationID string) {
	c.OrganizationID = organizationID
	c.require(contactFieldOrganizationID)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Contact) SetCreatedAt(createdAt time.Time) {
	c.CreatedAt = createdAt
	c.require(contactFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Contact) SetUpdatedAt(updatedAt time.Time) {
	c.UpdatedAt = updatedAt
	c.require(contactFieldUpdatedAt)
}

func (c *Contact) UnmarshalJSON(data []byte) error {
	type embed Contact
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = Contact(unmarshaler.embed)
	c.CreatedAt = unmarshaler.CreatedAt.Time()
	c.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *Contact) MarshalJSON() ([]byte, error) {
	type embed Contact
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed:     embed(*c),
		CreatedAt: internal.NewDateTime(c.CreatedAt),
		UpdatedAt: internal.NewDateTime(c.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *Contact) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	contactContactFieldFirstname = big.NewInt(1 << 0)
	contactContactFieldLastname  = big.NewInt(1 << 1)
	contactContactFieldJobtitle  = big.NewInt(1 << 2)
	contactContactFieldCompany   = big.NewInt(1 << 3)
)

type ContactContact struct {
	Firstname *string `json:"firstname,omitempty" url:"firstname,omitempty"`
	Lastname  *string `json:"lastname,omitempty" url:"lastname,omitempty"`
	Jobtitle  *string `json:"jobtitle,omitempty" url:"jobtitle,omitempty"`
	Company   *string `json:"company,omitempty" url:"company,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ContactContact) GetFirstname() *string {
	if c == nil {
		return nil
	}
	return c.Firstname
}

func (c *ContactContact) GetLastname() *string {
	if c == nil {
		return nil
	}
	return c.Lastname
}

func (c *ContactContact) GetJobtitle() *string {
	if c == nil {
		return nil
	}
	return c.Jobtitle
}

func (c *ContactContact) GetCompany() *string {
	if c == nil {
		return nil
	}
	return c.Company
}

func (c *ContactContact) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ContactContact) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetFirstname sets the Firstname field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ContactContact) SetFirstname(firstname *string) {
	c.Firstname = firstname
	c.require(contactContactFieldFirstname)
}

// SetLastname sets the Lastname field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ContactContact) SetLastname(lastname *string) {
	c.Lastname = lastname
	c.require(contactContactFieldLastname)
}

// SetJobtitle sets the Jobtitle field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ContactContact) SetJobtitle(jobtitle *string) {
	c.Jobtitle = jobtitle
	c.require(contactContactFieldJobtitle)
}

// SetCompany sets the Company field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ContactContact) SetCompany(company *string) {
	c.Company = company
	c.require(contactContactFieldCompany)
}

func (c *ContactContact) UnmarshalJSON(data []byte) error {
	type unmarshaler ContactContact
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ContactContact(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ContactContact) MarshalJSON() ([]byte, error) {
	type embed ContactContact
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ContactContact) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	paginationMetaFieldTotal      = big.NewInt(1 << 0)
	paginationMetaFieldPage       = big.NewInt(1 << 1)
	paginationMetaFieldPageSize   = big.NewInt(1 << 2)
	paginationMetaFieldTotalPages = big.NewInt(1 << 3)
)

type PaginationMeta struct {
	Total      float64 `json:"total" url:"total"`
	Page       float64 `json:"page" url:"page"`
	PageSize   float64 `json:"pageSize" url:"pageSize"`
	TotalPages float64 `json:"totalPages" url:"totalPages"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PaginationMeta) GetTotal() float64 {
	if p == nil {
		return 0
	}
	return p.Total
}

func (p *PaginationMeta) GetPage() float64 {
	if p == nil {
		return 0
	}
	return p.Page
}

func (p *PaginationMeta) GetPageSize() float64 {
	if p == nil {
		return 0
	}
	return p.PageSize
}

func (p *PaginationMeta) GetTotalPages() float64 {
	if p == nil {
		return 0
	}
	return p.TotalPages
}

func (p *PaginationMeta) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PaginationMeta) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginationMeta) SetTotal(total float64) {
	p.Total = total
	p.require(paginationMetaFieldTotal)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginationMeta) SetPage(page float64) {
	p.Page = page
	p.require(paginationMetaFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginationMeta) SetPageSize(pageSize float64) {
	p.PageSize = pageSize
	p.require(paginationMetaFieldPageSize)
}

// SetTotalPages sets the TotalPages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginationMeta) SetTotalPages(totalPages float64) {
	p.TotalPages = totalPages
	p.require(paginationMetaFieldTotalPages)
}

func (p *PaginationMeta) UnmarshalJSON(data []byte) error {
	type unmarshaler PaginationMeta
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PaginationMeta(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaginationMeta) MarshalJSON() ([]byte, error) {
	type embed PaginationMeta
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PaginationMeta) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	createContactResponseFieldData = big.NewInt(1 << 0)
)

type CreateContactResponse struct {
	Data *Contact `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateContactResponse) GetData() *Contact {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CreateContactResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateContactResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateContactResponse) SetData(data *Contact) {
	c.Data = data
	c.require(createContactResponseFieldData)
}

func (c *CreateContactResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateContactResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateContactResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateContactResponse) MarshalJSON() ([]byte, error) {
	type embed CreateContactResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateContactResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	getContactResponseFieldData = big.NewInt(1 << 0)
)

type GetContactResponse struct {
	Data *Contact `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetContactResponse) GetData() *Contact {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetContactResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetContactResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetContactResponse) SetData(data *Contact) {
	g.Data = data
	g.require(getContactResponseFieldData)
}

func (g *GetContactResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetContactResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetContactResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetContactResponse) MarshalJSON() ([]byte, error) {
	type embed GetContactResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetContactResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	listContactsResponseFieldData = big.NewInt(1 << 0)
	listContactsResponseFieldMeta = big.NewInt(1 << 1)
)

type ListContactsResponse struct {
	Data []*Contact      `json:"data" url:"data"`
	Meta *PaginationMeta `json:"meta" url:"meta"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListContactsResponse) GetData() []*Contact {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListContactsResponse) GetMeta() *PaginationMeta {
	if l == nil {
		return nil
	}
	return l.Meta
}

func (l *ListContactsResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListContactsResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListContactsResponse) SetData(data []*Contact) {
	l.Data = data
	l.require(listContactsResponseFieldData)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListContactsResponse) SetMeta(meta *PaginationMeta) {
	l.Meta = meta
	l.require(listContactsResponseFieldMeta)
}

func (l *ListContactsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListContactsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListContactsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListContactsResponse) MarshalJSON() ([]byte, error) {
	type embed ListContactsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListContactsResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
