// Code generated by Fern. DO NOT EDIT.

package informly

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/informlyco/informly-go/internal"
	big "math/big"
	time "time"
)

var (
	createContactFieldEmail        = big.NewInt(1 << 0)
	createContactFieldPhone        = big.NewInt(1 << 1)
	createContactFieldFirstname    = big.NewInt(1 << 2)
	createContactFieldLastname     = big.NewInt(1 << 3)
	createContactFieldJobtitle     = big.NewInt(1 << 4)
	createContactFieldCompany      = big.NewInt(1 << 5)
	createContactFieldSegmentIDs   = big.NewInt(1 << 6)
	createContactFieldReferralCode = big.NewInt(1 << 7)
)

type CreateContact struct {
	// Email address. Required if phone is not provided.
	Email *string `json:"email,omitempty" url:"-"`
	// Phone number in E.164 format. Required if email is not provided.
	Phone *string `json:"phone,omitempty" url:"-"`
	// First name of the contact
	Firstname *string `json:"firstname,omitempty" url:"-"`
	// Last name of the contact
	Lastname *string `json:"lastname,omitempty" url:"-"`
	// Job title of the contact
	Jobtitle *string `json:"jobtitle,omitempty" url:"-"`
	// Company or organization name
	Company *string `json:"company,omitempty" url:"-"`
	// Segment IDs to assign to the contact
	SegmentIDs []string `json:"segmentIds,omitempty" url:"-"`
	// Referral code to redeem for this contact
	ReferralCode *string `json:"referralCode,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateContact) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateContact) SetEmail(email *string) {
	c.Email = email
	c.require(createContactFieldEmail)
}

// SetPhone sets the Phone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateContact) SetPhone(phone *string) {
	c.Phone = phone
	c.require(createContactFieldPhone)
}

// SetFirstname sets the Firstname field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateContact) SetFirstname(firstname *string) {
	c.Firstname = firstname
	c.require(createContactFieldFirstname)
}

// SetLastname sets the Lastname field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateContact) SetLastname(lastname *string) {
	c.Lastname = lastname
	c.require(createContactFieldLastname)
}

// SetJobtitle sets the Jobtitle field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateContact) SetJobtitle(jobtitle *string) {
	c.Jobtitle = jobtitle
	c.require(createContactFieldJobtitle)
}

// SetCompany sets the Company field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateContact) SetCompany(company *string) {
	c.Company = company
	c.require(createContactFieldCompany)
}

// SetSegmentIDs sets the SegmentIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateContact) SetSegmentIDs(segmentIDs []string) {
	c.SegmentIDs = segmentIDs
	c.require(createContactFieldSegmentIDs)
}

// SetReferralCode sets the ReferralCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateContact) SetReferralCode(referralCode *string) {
	c.ReferralCode = referralCode
	c.require(createContactFieldReferralCode)
}

func (c *CreateContact) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateContact
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateContact(body)
	return nil
}

func (c *CreateContact) MarshalJSON() ([]byte, error) {
	type embed CreateContact
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deleteContactRequestFieldID = big.NewInt(1 << 0)
)

type DeleteContactRequest struct {
	// Unique identifier of the resource
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteContactRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteContactRequest) SetID(id string) {
	d.ID = id
	d.require(deleteContactRequestFieldID)
}

var (
	deleteContactsFieldIDs = big.NewInt(1 << 0)
)

type DeleteContacts struct {
	// Contact IDs to delete
	IDs []string `json:"ids" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteContacts) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetIDs sets the IDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteContacts) SetIDs(ids []string) {
	d.IDs = ids
	d.require(deleteContactsFieldIDs)
}

func (d *DeleteContacts) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteContacts
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*d = DeleteContacts(body)
	return nil
}

func (d *DeleteContacts) MarshalJSON() ([]byte, error) {
	type embed DeleteContacts
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getContactRequestFieldID = big.NewInt(1 << 0)
)

type GetContactRequest struct {
	// Unique identifier of the resource
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetContactRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetContactRequest) SetID(id string) {
	g.ID = id
	g.require(getContactRequestFieldID)
}

var (
	listContactsRequestFieldPage     = big.NewInt(1 << 0)
	listContactsRequestFieldPageSize = big.NewInt(1 << 1)
)

type ListContactsRequest struct {
	// Page number (1-indexed)
	Page *int `json:"-" url:"page,omitempty"`
	// Number of items per page (1-100)
	PageSize *int `json:"-" url:"pageSize,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListContactsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListContactsRequest) SetPage(page *int) {
	l.Page = page
	l.require(listContactsRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListContactsRequest) SetPageSize(pageSize *int) {
	l.PageSize = pageSize
	l.require(listContactsRequestFieldPageSize)
}

var (
	contactFieldID             = big.NewInt(1 << 0)
	contactFieldEmail          = big.NewInt(1 << 1)
	contactFieldPhone          = big.NewInt(1 << 2)
	contactFieldContact        = big.NewInt(1 << 3)
	contactFieldSegments       = big.NewInt(1 << 4)
	contactFieldOrganizationID = big.NewInt(1 << 5)
	contactFieldCreatedAt      = big.NewInt(1 << 6)
	contactFieldUpdatedAt      = big.NewInt(1 << 7)
)

type Contact struct {
	// Unique identifier for the contact
	ID string `json:"id" url:"id"`
	// Email address of the contact
	Email *string `json:"email,omitempty" url:"email,omitempty"`
	// Phone number in E.164 format
	Phone   *string         `json:"phone,omitempty" url:"phone,omitempty"`
	Contact *ContactContact `json:"contact" url:"contact"`
	// Segments assigned to this contact
	Segments []*ContactSegmentsItem `json:"segments,omitempty" url:"segments,omitempty"`
	// ID of the organization this contact belongs to
	OrganizationID string `json:"organizationId" url:"organizationId"`
	// Timestamp when the contact was created
	CreatedAt time.Time `json:"createdAt" url:"createdAt"`
	// Timestamp when the contact was last updated
	UpdatedAt time.Time `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *Contact) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *Contact) GetEmail() *string {
	if c == nil {
		return nil
	}
	return c.Email
}

func (c *Contact) GetPhone() *string {
	if c == nil {
		return nil
	}
	return c.Phone
}

func (c *Contact) GetContact() *ContactContact {
	if c == nil {
		return nil
	}
	return c.Contact
}

func (c *Contact) GetSegments() []*ContactSegmentsItem {
	if c == nil {
		return nil
	}
	return c.Segments
}

func (c *Contact) GetOrganizationID() string {
	if c == nil {
		return ""
	}
	return c.OrganizationID
}

func (c *Contact) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *Contact) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}

func (c *Contact) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *Contact) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Contact) SetID(id string) {
	c.ID = id
	c.require(contactFieldID)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Contact) SetEmail(email *string) {
	c.Email = email
	c.require(contactFieldEmail)
}

// SetPhone sets the Phone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Contact) SetPhone(phone *string) {
	c.Phone = phone
	c.require(contactFieldPhone)
}

// SetContact sets the Contact field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Contact) SetContact(contact *ContactContact) {
	c.Contact = contact
	c.require(contactFieldContact)
}

// SetSegments sets the Segments field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Contact) SetSegments(segments []*ContactSegmentsItem) {
	c.Segments = segments
	c.require(contactFieldSegments)
}

// SetOrganizationID sets the OrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Contact) SetOrganizationID(organizationID string) {
	c.OrganizationID = organizationID
	c.require(contactFieldOrganizationID)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Contact) SetCreatedAt(createdAt time.Time) {
	c.CreatedAt = createdAt
	c.require(contactFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Contact) SetUpdatedAt(updatedAt time.Time) {
	c.UpdatedAt = updatedAt
	c.require(contactFieldUpdatedAt)
}

func (c *Contact) UnmarshalJSON(data []byte) error {
	type embed Contact
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = Contact(unmarshaler.embed)
	c.CreatedAt = unmarshaler.CreatedAt.Time()
	c.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *Contact) MarshalJSON() ([]byte, error) {
	type embed Contact
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed:     embed(*c),
		CreatedAt: internal.NewDateTime(c.CreatedAt),
		UpdatedAt: internal.NewDateTime(c.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *Contact) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	contactContactFieldFirstname = big.NewInt(1 << 0)
	contactContactFieldLastname  = big.NewInt(1 << 1)
	contactContactFieldJobtitle  = big.NewInt(1 << 2)
	contactContactFieldCompany   = big.NewInt(1 << 3)
)

type ContactContact struct {
	// First name of the contact
	Firstname *string `json:"firstname,omitempty" url:"firstname,omitempty"`
	// Last name of the contact
	Lastname *string `json:"lastname,omitempty" url:"lastname,omitempty"`
	// Job title of the contact
	Jobtitle *string `json:"jobtitle,omitempty" url:"jobtitle,omitempty"`
	// Company or organization name
	Company *string `json:"company,omitempty" url:"company,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ContactContact) GetFirstname() *string {
	if c == nil {
		return nil
	}
	return c.Firstname
}

func (c *ContactContact) GetLastname() *string {
	if c == nil {
		return nil
	}
	return c.Lastname
}

func (c *ContactContact) GetJobtitle() *string {
	if c == nil {
		return nil
	}
	return c.Jobtitle
}

func (c *ContactContact) GetCompany() *string {
	if c == nil {
		return nil
	}
	return c.Company
}

func (c *ContactContact) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ContactContact) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetFirstname sets the Firstname field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ContactContact) SetFirstname(firstname *string) {
	c.Firstname = firstname
	c.require(contactContactFieldFirstname)
}

// SetLastname sets the Lastname field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ContactContact) SetLastname(lastname *string) {
	c.Lastname = lastname
	c.require(contactContactFieldLastname)
}

// SetJobtitle sets the Jobtitle field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ContactContact) SetJobtitle(jobtitle *string) {
	c.Jobtitle = jobtitle
	c.require(contactContactFieldJobtitle)
}

// SetCompany sets the Company field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ContactContact) SetCompany(company *string) {
	c.Company = company
	c.require(contactContactFieldCompany)
}

func (c *ContactContact) UnmarshalJSON(data []byte) error {
	type unmarshaler ContactContact
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ContactContact(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ContactContact) MarshalJSON() ([]byte, error) {
	type embed ContactContact
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ContactContact) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	contactSegmentsItemFieldSegmentID  = big.NewInt(1 << 0)
	contactSegmentsItemFieldAssignedAt = big.NewInt(1 << 1)
)

type ContactSegmentsItem struct {
	// Segment identifier
	SegmentID string `json:"segmentId" url:"segmentId"`
	// When the segment was assigned
	AssignedAt time.Time `json:"assignedAt" url:"assignedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ContactSegmentsItem) GetSegmentID() string {
	if c == nil {
		return ""
	}
	return c.SegmentID
}

func (c *ContactSegmentsItem) GetAssignedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.AssignedAt
}

func (c *ContactSegmentsItem) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ContactSegmentsItem) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSegmentID sets the SegmentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ContactSegmentsItem) SetSegmentID(segmentID string) {
	c.SegmentID = segmentID
	c.require(contactSegmentsItemFieldSegmentID)
}

// SetAssignedAt sets the AssignedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ContactSegmentsItem) SetAssignedAt(assignedAt time.Time) {
	c.AssignedAt = assignedAt
	c.require(contactSegmentsItemFieldAssignedAt)
}

func (c *ContactSegmentsItem) UnmarshalJSON(data []byte) error {
	type embed ContactSegmentsItem
	var unmarshaler = struct {
		embed
		AssignedAt *internal.DateTime `json:"assignedAt"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = ContactSegmentsItem(unmarshaler.embed)
	c.AssignedAt = unmarshaler.AssignedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ContactSegmentsItem) MarshalJSON() ([]byte, error) {
	type embed ContactSegmentsItem
	var marshaler = struct {
		embed
		AssignedAt *internal.DateTime `json:"assignedAt"`
	}{
		embed:      embed(*c),
		AssignedAt: internal.NewDateTime(c.AssignedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ContactSegmentsItem) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	paginationMetaFieldTotal      = big.NewInt(1 << 0)
	paginationMetaFieldPage       = big.NewInt(1 << 1)
	paginationMetaFieldPageSize   = big.NewInt(1 << 2)
	paginationMetaFieldTotalPages = big.NewInt(1 << 3)
)

type PaginationMeta struct {
	// Total number of items across all pages
	Total float64 `json:"total" url:"total"`
	// Current page number
	Page float64 `json:"page" url:"page"`
	// Number of items per page
	PageSize float64 `json:"pageSize" url:"pageSize"`
	// Total number of pages
	TotalPages float64 `json:"totalPages" url:"totalPages"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PaginationMeta) GetTotal() float64 {
	if p == nil {
		return 0
	}
	return p.Total
}

func (p *PaginationMeta) GetPage() float64 {
	if p == nil {
		return 0
	}
	return p.Page
}

func (p *PaginationMeta) GetPageSize() float64 {
	if p == nil {
		return 0
	}
	return p.PageSize
}

func (p *PaginationMeta) GetTotalPages() float64 {
	if p == nil {
		return 0
	}
	return p.TotalPages
}

func (p *PaginationMeta) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PaginationMeta) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginationMeta) SetTotal(total float64) {
	p.Total = total
	p.require(paginationMetaFieldTotal)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginationMeta) SetPage(page float64) {
	p.Page = page
	p.require(paginationMetaFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginationMeta) SetPageSize(pageSize float64) {
	p.PageSize = pageSize
	p.require(paginationMetaFieldPageSize)
}

// SetTotalPages sets the TotalPages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginationMeta) SetTotalPages(totalPages float64) {
	p.TotalPages = totalPages
	p.require(paginationMetaFieldTotalPages)
}

func (p *PaginationMeta) UnmarshalJSON(data []byte) error {
	type unmarshaler PaginationMeta
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PaginationMeta(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaginationMeta) MarshalJSON() ([]byte, error) {
	type embed PaginationMeta
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PaginationMeta) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	createContactResponseFieldData = big.NewInt(1 << 0)
)

type CreateContactResponse struct {
	Data *Contact `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateContactResponse) GetData() *Contact {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CreateContactResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateContactResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateContactResponse) SetData(data *Contact) {
	c.Data = data
	c.require(createContactResponseFieldData)
}

func (c *CreateContactResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateContactResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateContactResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateContactResponse) MarshalJSON() ([]byte, error) {
	type embed CreateContactResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateContactResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	deleteContactResponseFieldData = big.NewInt(1 << 0)
)

type DeleteContactResponse struct {
	Data *Contact `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeleteContactResponse) GetData() *Contact {
	if d == nil {
		return nil
	}
	return d.Data
}

func (d *DeleteContactResponse) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeleteContactResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteContactResponse) SetData(data *Contact) {
	d.Data = data
	d.require(deleteContactResponseFieldData)
}

func (d *DeleteContactResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteContactResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteContactResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteContactResponse) MarshalJSON() ([]byte, error) {
	type embed DeleteContactResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeleteContactResponse) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	deleteContactsResponseFieldData = big.NewInt(1 << 0)
)

type DeleteContactsResponse struct {
	Data *DeleteContactsResponseData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeleteContactsResponse) GetData() *DeleteContactsResponseData {
	if d == nil {
		return nil
	}
	return d.Data
}

func (d *DeleteContactsResponse) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeleteContactsResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteContactsResponse) SetData(data *DeleteContactsResponseData) {
	d.Data = data
	d.require(deleteContactsResponseFieldData)
}

func (d *DeleteContactsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteContactsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteContactsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteContactsResponse) MarshalJSON() ([]byte, error) {
	type embed DeleteContactsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeleteContactsResponse) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	deleteContactsResponseDataFieldCount = big.NewInt(1 << 0)
)

type DeleteContactsResponseData struct {
	// Number of contacts deleted
	Count float64 `json:"count" url:"count"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeleteContactsResponseData) GetCount() float64 {
	if d == nil {
		return 0
	}
	return d.Count
}

func (d *DeleteContactsResponseData) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeleteContactsResponseData) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteContactsResponseData) SetCount(count float64) {
	d.Count = count
	d.require(deleteContactsResponseDataFieldCount)
}

func (d *DeleteContactsResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteContactsResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteContactsResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteContactsResponseData) MarshalJSON() ([]byte, error) {
	type embed DeleteContactsResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeleteContactsResponseData) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	getContactResponseFieldData = big.NewInt(1 << 0)
)

type GetContactResponse struct {
	Data *Contact `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetContactResponse) GetData() *Contact {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetContactResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetContactResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetContactResponse) SetData(data *Contact) {
	g.Data = data
	g.require(getContactResponseFieldData)
}

func (g *GetContactResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetContactResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetContactResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetContactResponse) MarshalJSON() ([]byte, error) {
	type embed GetContactResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetContactResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	listContactsResponseFieldData = big.NewInt(1 << 0)
	listContactsResponseFieldMeta = big.NewInt(1 << 1)
)

type ListContactsResponse struct {
	Data []*Contact      `json:"data" url:"data"`
	Meta *PaginationMeta `json:"meta" url:"meta"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListContactsResponse) GetData() []*Contact {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListContactsResponse) GetMeta() *PaginationMeta {
	if l == nil {
		return nil
	}
	return l.Meta
}

func (l *ListContactsResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListContactsResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListContactsResponse) SetData(data []*Contact) {
	l.Data = data
	l.require(listContactsResponseFieldData)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListContactsResponse) SetMeta(meta *PaginationMeta) {
	l.Meta = meta
	l.require(listContactsResponseFieldMeta)
}

func (l *ListContactsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListContactsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListContactsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListContactsResponse) MarshalJSON() ([]byte, error) {
	type embed ListContactsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListContactsResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	updateContactResponseFieldData = big.NewInt(1 << 0)
)

type UpdateContactResponse struct {
	Data *Contact `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateContactResponse) GetData() *Contact {
	if u == nil {
		return nil
	}
	return u.Data
}

func (u *UpdateContactResponse) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UpdateContactResponse) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateContactResponse) SetData(data *Contact) {
	u.Data = data
	u.require(updateContactResponseFieldData)
}

func (u *UpdateContactResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateContactResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateContactResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateContactResponse) MarshalJSON() ([]byte, error) {
	type embed UpdateContactResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateContactResponse) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	updateContactFieldID         = big.NewInt(1 << 0)
	updateContactFieldEmail      = big.NewInt(1 << 1)
	updateContactFieldPhone      = big.NewInt(1 << 2)
	updateContactFieldFirstname  = big.NewInt(1 << 3)
	updateContactFieldLastname   = big.NewInt(1 << 4)
	updateContactFieldJobtitle   = big.NewInt(1 << 5)
	updateContactFieldCompany    = big.NewInt(1 << 6)
	updateContactFieldSegmentIDs = big.NewInt(1 << 7)
)

type UpdateContact struct {
	// Unique identifier of the resource
	ID string `json:"-" url:"-"`
	// Email address of the contact
	Email *string `json:"email,omitempty" url:"-"`
	// Phone number in E.164 format (e.g. +14155552671)
	Phone *string `json:"phone,omitempty" url:"-"`
	// First name of the contact
	Firstname *string `json:"firstname,omitempty" url:"-"`
	// Last name of the contact
	Lastname *string `json:"lastname,omitempty" url:"-"`
	// Job title of the contact
	Jobtitle *string `json:"jobtitle,omitempty" url:"-"`
	// Company or organization name
	Company *string `json:"company,omitempty" url:"-"`
	// Segment IDs to assign (replaces existing segments)
	SegmentIDs []string `json:"segmentIds,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateContact) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateContact) SetID(id string) {
	u.ID = id
	u.require(updateContactFieldID)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateContact) SetEmail(email *string) {
	u.Email = email
	u.require(updateContactFieldEmail)
}

// SetPhone sets the Phone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateContact) SetPhone(phone *string) {
	u.Phone = phone
	u.require(updateContactFieldPhone)
}

// SetFirstname sets the Firstname field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateContact) SetFirstname(firstname *string) {
	u.Firstname = firstname
	u.require(updateContactFieldFirstname)
}

// SetLastname sets the Lastname field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateContact) SetLastname(lastname *string) {
	u.Lastname = lastname
	u.require(updateContactFieldLastname)
}

// SetJobtitle sets the Jobtitle field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateContact) SetJobtitle(jobtitle *string) {
	u.Jobtitle = jobtitle
	u.require(updateContactFieldJobtitle)
}

// SetCompany sets the Company field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateContact) SetCompany(company *string) {
	u.Company = company
	u.require(updateContactFieldCompany)
}

// SetSegmentIDs sets the SegmentIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateContact) SetSegmentIDs(segmentIDs []string) {
	u.SegmentIDs = segmentIDs
	u.require(updateContactFieldSegmentIDs)
}

func (u *UpdateContact) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateContact
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateContact(body)
	return nil
}

func (u *UpdateContact) MarshalJSON() ([]byte, error) {
	type embed UpdateContact
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}
