// Code generated by Fern. DO NOT EDIT.

package api

import (
	core "github.com/informlyco/informly-go/core"
	internal "github.com/informlyco/informly-go/internal"
)

var ErrorCodes internal.ErrorCodes = internal.ErrorCodes{
	401: func(apiError *core.APIError) error {
		return &UnauthorizedError{
			APIError: apiError,
		}
	},
	403: func(apiError *core.APIError) error {
		return &ForbiddenError{
			APIError: apiError,
		}
	},
	400: func(apiError *core.APIError) error {
		return &BadRequestError{
			APIError: apiError,
		}
	},
	404: func(apiError *core.APIError) error {
		return &NotFoundError{
			APIError: apiError,
		}
	},
}
