// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/informlyco/informly-go/internal"
	big "math/big"
)

var (
	getHealthResponseFieldData = big.NewInt(1 << 0)
)

type GetHealthResponse struct {
	Data *GetHealthResponseData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetHealthResponse) GetData() *GetHealthResponseData {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetHealthResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetHealthResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetHealthResponse) SetData(data *GetHealthResponseData) {
	g.Data = data
	g.require(getHealthResponseFieldData)
}

func (g *GetHealthResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetHealthResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetHealthResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetHealthResponse) MarshalJSON() ([]byte, error) {
	type embed GetHealthResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetHealthResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getHealthResponseDataFieldStatus    = big.NewInt(1 << 0)
	getHealthResponseDataFieldService   = big.NewInt(1 << 1)
	getHealthResponseDataFieldVersion   = big.NewInt(1 << 2)
	getHealthResponseDataFieldTimestamp = big.NewInt(1 << 3)
)

type GetHealthResponseData struct {
	Status    string `json:"status" url:"status"`
	Service   string `json:"service" url:"service"`
	Version   string `json:"version" url:"version"`
	Timestamp string `json:"timestamp" url:"timestamp"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetHealthResponseData) GetStatus() string {
	if g == nil {
		return ""
	}
	return g.Status
}

func (g *GetHealthResponseData) GetService() string {
	if g == nil {
		return ""
	}
	return g.Service
}

func (g *GetHealthResponseData) GetVersion() string {
	if g == nil {
		return ""
	}
	return g.Version
}

func (g *GetHealthResponseData) GetTimestamp() string {
	if g == nil {
		return ""
	}
	return g.Timestamp
}

func (g *GetHealthResponseData) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetHealthResponseData) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetHealthResponseData) SetStatus(status string) {
	g.Status = status
	g.require(getHealthResponseDataFieldStatus)
}

// SetService sets the Service field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetHealthResponseData) SetService(service string) {
	g.Service = service
	g.require(getHealthResponseDataFieldService)
}

// SetVersion sets the Version field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetHealthResponseData) SetVersion(version string) {
	g.Version = version
	g.require(getHealthResponseDataFieldVersion)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetHealthResponseData) SetTimestamp(timestamp string) {
	g.Timestamp = timestamp
	g.require(getHealthResponseDataFieldTimestamp)
}

func (g *GetHealthResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler GetHealthResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetHealthResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetHealthResponseData) MarshalJSON() ([]byte, error) {
	type embed GetHealthResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetHealthResponseData) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}
