// Code generated by Fern. DO NOT EDIT.

package informly

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/informlyco/informly-go/internal"
	big "math/big"
)

var (
	segmentFieldID    = big.NewInt(1 << 0)
	segmentFieldTitle = big.NewInt(1 << 1)
	segmentFieldColor = big.NewInt(1 << 2)
)

type Segment struct {
	// Unique identifier for the segment
	ID string `json:"id" url:"id"`
	// Segment name
	Title string `json:"title" url:"title"`
	// Hex color for the segment
	Color *string `json:"color,omitempty" url:"color,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *Segment) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *Segment) GetTitle() string {
	if s == nil {
		return ""
	}
	return s.Title
}

func (s *Segment) GetColor() *string {
	if s == nil {
		return nil
	}
	return s.Color
}

func (s *Segment) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *Segment) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Segment) SetID(id string) {
	s.ID = id
	s.require(segmentFieldID)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Segment) SetTitle(title string) {
	s.Title = title
	s.require(segmentFieldTitle)
}

// SetColor sets the Color field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Segment) SetColor(color *string) {
	s.Color = color
	s.require(segmentFieldColor)
}

func (s *Segment) UnmarshalJSON(data []byte) error {
	type unmarshaler Segment
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = Segment(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *Segment) MarshalJSON() ([]byte, error) {
	type embed Segment
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *Segment) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	listSegmentsResponseFieldData = big.NewInt(1 << 0)
)

type ListSegmentsResponse struct {
	Data []*Segment `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListSegmentsResponse) GetData() []*Segment {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListSegmentsResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListSegmentsResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSegmentsResponse) SetData(data []*Segment) {
	l.Data = data
	l.require(listSegmentsResponseFieldData)
}

func (l *ListSegmentsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListSegmentsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListSegmentsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListSegmentsResponse) MarshalJSON() ([]byte, error) {
	type embed ListSegmentsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListSegmentsResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
