// Code generated by Fern. DO NOT EDIT.

package health

import (
	context "context"
	informlygo "github.com/informlyco/informly-go"
	core "github.com/informlyco/informly-go/core"
	internal "github.com/informlyco/informly-go/internal"
	option "github.com/informlyco/informly-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Returns the health status of the API service
func (c *Client) HealthCheck(
	ctx context.Context,
	opts ...option.RequestOption,
) (*informlygo.GetHealthResponse, error) {
	response, err := c.WithRawResponse.HealthCheck(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
