// Code generated by Fern. DO NOT EDIT.

package contacts

import (
	context "context"
	informlygo "github.com/informlyco/informly-go"
	core "github.com/informlyco/informly-go/core"
	internal "github.com/informlyco/informly-go/internal"
	option "github.com/informlyco/informly-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) ListContacts(
	ctx context.Context,
	request *informlygo.ListContactsRequest,
	opts ...option.RequestOption,
) (*informlygo.ListContactsResponse, error) {
	response, err := c.WithRawResponse.ListContacts(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CreateContact(
	ctx context.Context,
	request *informlygo.CreateContact,
	opts ...option.RequestOption,
) (*informlygo.CreateContactResponse, error) {
	response, err := c.WithRawResponse.CreateContact(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetContact(
	ctx context.Context,
	request *informlygo.GetContactRequest,
	opts ...option.RequestOption,
) (*informlygo.GetContactResponse, error) {
	response, err := c.WithRawResponse.GetContact(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
