// Code generated by Fern. DO NOT EDIT.

package contacts

import (
	context "context"

	informly "github.com/informlyco/informly-go"
	core "github.com/informlyco/informly-go/core"
	internal "github.com/informlyco/informly-go/internal"
	option "github.com/informlyco/informly-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) ListContacts(
	ctx context.Context,
	request *informly.ListContactsRequest,
	opts ...option.RequestOption,
) (*informly.ListContactsResponse, error) {
	response, err := c.WithRawResponse.ListContacts(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Creates a new contact or updates an existing one if a contact with the same email or phone already exists. Optionally assigns segments and redeems a referral code.
func (c *Client) CreateContact(
	ctx context.Context,
	request *informly.CreateContact,
	opts ...option.RequestOption,
) (*informly.CreateContactResponse, error) {
	response, err := c.WithRawResponse.CreateContact(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) DeleteContacts(
	ctx context.Context,
	request *informly.DeleteContacts,
	opts ...option.RequestOption,
) (*informly.DeleteContactsResponse, error) {
	response, err := c.WithRawResponse.DeleteContacts(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetContact(
	ctx context.Context,
	request *informly.GetContactRequest,
	opts ...option.RequestOption,
) (*informly.GetContactResponse, error) {
	response, err := c.WithRawResponse.GetContact(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Updates an existing contact's fields. If segmentIds is provided, it replaces all existing segment assignments.
func (c *Client) UpdateContact(
	ctx context.Context,
	request *informly.UpdateContact,
	opts ...option.RequestOption,
) (*informly.UpdateContactResponse, error) {
	response, err := c.WithRawResponse.UpdateContact(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) DeleteContact(
	ctx context.Context,
	request *informly.DeleteContactRequest,
	opts ...option.RequestOption,
) (*informly.DeleteContactResponse, error) {
	response, err := c.WithRawResponse.DeleteContact(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
