// Code generated by Fern. DO NOT EDIT.

package contacts

import (
	context "context"
	informlygo "github.com/informlyco/informly-go"
	core "github.com/informlyco/informly-go/core"
	internal "github.com/informlyco/informly-go/internal"
	option "github.com/informlyco/informly-go/option"
	http "net/http"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) ListContacts(
	ctx context.Context,
	request *informlygo.ListContactsRequest,
	opts ...option.RequestOption,
) (*core.Response[*informlygo.ListContactsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:4000/api/v1",
	)
	endpointURL := baseURL + "/contacts"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *informlygo.ListContactsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(informlygo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*informlygo.ListContactsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateContact(
	ctx context.Context,
	request *informlygo.CreateContact,
	opts ...option.RequestOption,
) (*core.Response[*informlygo.CreateContactResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:4000/api/v1",
	)
	endpointURL := baseURL + "/contacts"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *informlygo.CreateContactResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(informlygo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*informlygo.CreateContactResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetContact(
	ctx context.Context,
	request *informlygo.GetContactRequest,
	opts ...option.RequestOption,
) (*core.Response[*informlygo.GetContactResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:4000/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/contacts/%v",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *informlygo.GetContactResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(informlygo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*informlygo.GetContactResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
